apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hammy
  name: hammy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hammy
  template:
    metadata:
      labels:
        app: hammy
    spec:
      containers:
        - image: gohammy/hammy
          name: hammy
          ports:
            - containerPort: 9090
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: hammy
spec:
  selector:
    app: hammy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: LoadBalancer
