name: "Build and Upload Docker Image"
on:
  push:
    branches-ignore:
      - main
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Read hammyVersion from config.yaml
        id: read-version
        run: |
          hammyVersion=$(grep 'hammyVersion' config.yaml | awk -F": " '{print $2}')
          echo "hammyVersion=$hammyVersion" >> $GITHUB_ENV

      - name: Build Docker image with version tag
        run: docker build -t ${{ secrets.DOCKER_USER }}/hammy:dev-${{ env.hammyVersion }} .

      - name: Push Docker image with version tag
        run: docker push ${{ secrets.DOCKER_USER }}/hammy:dev-${{ env.hammyVersion }}
