name: "Build and Upload Docker Image"
on:
  push:
    branches:
      - main
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with version tag
        run: docker build -t ${{ secrets.DOCKER_USER }}/hammy:v1 .

      - name: Push Docker image with version tag
        run: docker push ${{ secrets.DOCKER_USER }}/hammy:v1

      - name: Build Docker image with latest tag
        run: docker build -t ${{ secrets.DOCKER_USER }}/hammy:latest .

      - name: Push Docker image with latest
        run: docker push ${{ secrets.DOCKER_USER }}/hammy:latest
